### ISSUE TITLE
OpenMRS CORS issue on third party integration

### ISSUE THREAD

**Issue by madhavgritfeat** [Bahmni/bahmni-docker#49]
I am trying to create custom app out of OpenMRS and Bahmni. I have deployed all the services using docker, from this: [GitHub - Bahmni/bahmni-docker: Configuration required to build and run bahmni docker images](https://github.com/Bahmni/bahmni-docker). I am using <base_URL>/openmrs/ws/rest/v1/session API for auth and it is working fine on postman, but when I try the same using webapp, it shows CORS issue on API call. Can help?
<img width="559" alt="image" src="https://github.com/Bahmni/bahmni-docker/assets/78906845/45164467-d080-4ae6-a25f-b83d68928ab0">

**Comment by gsluthra** [comment]
The Q&A forum for Bahmni is here: https://talk.openmrs.org/c/software/bahmni/36
Can you re-post your question here?

**Comment by madhavgritfeat** [comment]
posted: https://talk.openmrs.org/t/openmrs-cors-issue-on-third-party-integration/39876. This however, seems bug to me
